/* THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY. */
/* eslint-disable */
/* prettier-ignore */

import {MessageLoader, TypedIntlMessageGetter, HandlerFunction, HookFunction, LinkFunction} from '@discord/intl';

export declare const messagesLoader: MessageLoader;

declare const messages: {
  /**
   * Key: `MZL7pq`
   *
   * ### Definition
   * ```text
   * Auto Rotation
   * ```
   *
   * ### Problems
   *
   * Missing translations: `it`, `pl`
   */
  STATISTIC_COUNTER_AUTO_ROTATION: TypedIntlMessageGetter<{}>;
  /**
   * Key: `b6zDCw`
   *
   * ### Definition
   * ```text
   * Pause on Hover
   * ```
   *
   * ### Problems
   *
   * Missing translations: `it`, `pl`
   */
  STATISTIC_COUNTER_PAUSE_ON_HOVER: TypedIntlMessageGetter<{}>;
  /**
   * Key: `DdQITk`
   *
   * ### Definition
   * ```text
   * Preserve Last Counter
   * ```
   *
   * ### Problems
   *
   * Missing translations: `it`, `pl`
   */
  STATISTIC_COUNTER_PRESERVE_LAST_COUNTER: TypedIntlMessageGetter<{}>;
  /**
   * Key: `lhY5uL`
   *
   * ### Definition
   * ```text
   * Rotation Interval
   * ```
   *
   * ### Problems
   *
   * Missing translations: `it`, `pl`
   */
  STATISTIC_COUNTER_ROTATION_INTERVAL: TypedIntlMessageGetter<{}>;
  /**
   * Key: `suC9Pj`
   *
   * ### Definition
   * ```text
   * Show {counter}
   * ```
   *
   * ### Problems
   *
   * Missing translations: `it`, `pl`
   */
  STATISTIC_COUNTER_SHOW_COUNTER: TypedIntlMessageGetter<{ counter: any }>;
  /**
   * Key: `s2hbJS`
   *
   * ### Definition
   * ```text
   * View Order
   * ```
   *
   * ### Problems
   *
   * Missing translations: `it`, `pl`
   */
  STATISTIC_COUNTER_VIEW_ORDER: TypedIntlMessageGetter<{}>;
  /**
   * Key: `9lNenp`
   *
   * ### Definition
   * ```text
   * Visibility
   * ```
   *
   * ### Problems
   *
   * Missing translations: `it`, `pl`
   */
  STATISTIC_COUNTER_VISIBILITY: TypedIntlMessageGetter<{}>;
};
export default messages;
